apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: traditional-my-app-release
  namespace: default
spec:
  replicas: 5
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: traditional-my-app
  template:
    metadata:
      labels:
        app: traditional-my-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: my-app
          image: ghcr.io/helennelson139/rl-project_dqn_lstm_agent_driven_canary_release/my-app:c41baa1
          env:
            - name: APP_SCENARIO
              value: "normal"
            - name: APP_VERSION
              value: "traditional-v1"
          ports:
            - name: http
              containerPort: 8080

  strategy:
    canary:
      dynamicStableScale: true
      maxSurge: 1
      maxUnavailable: 0
      canaryService: traditional-my-app-canary
      stableService: traditional-my-app-stable
      trafficRouting:
        nginx:
          stableIngress: traditional-my-app-ingress

      # KHỐI STEPS ĐÃ ĐƯỢC THỤT LÙI VÀO TRONG CANARY:
      steps:
        - setWeight: 10
        - pause:
            duration: 30s
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 30s
        - setWeight: 100
